spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seowj?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafy
    password: ssafy

  jpa:
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: travelly7@gmail.com
    password: jccs donl wbew kace
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
